repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check src tests
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy src
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
